spring:
  application:
    name: springboot-observability
management:
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - "*"
        exclude:
          - beans
          - threaddump
#      base-path: /my-measures
#  server:
#    port: 9000